{% set name = "klaus" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/klaus-{{ version }}.tar.gz
  sha256: 8829af0e8a035fe6d8d4c19d3027a829b91ce0b9923ae6efb2acb884bbcdebe0

build:
  noarch: python
  entry_points:
    - klaus=klaus.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - dulwich >=0.19.3
    - flask
    - httpauth
    - humanize
    - pygments
    - python >=3.5
    - werkzeug >=0.15.0

test:
  imports:
    - klaus
  commands:
    - pip check
    - klaus --help
  requires:
    - pip

about:
  home: https://github.com/jonashaag/klaus
  summary: The first Git web viewer that Just Works™.
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jonashaag
